name: CI

on: [push, pull_request]

env:
  CI: true

jobs:
  buildandtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Cypress run
        uses: cypress-io/github-action@v5

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Print Environment Variable
        run: echo $MY_ENV_VAR
