name: CI/CD Python Pipeline

on: [push, pull_request]
env:
  VERCEL_ORG_ID: ${{ secrets.VERCELORGID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCELPYTHONPROJECTID }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./recommendation-system"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          working-directory: ${{env.working-directory}}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          working-directory: ${{env.working-directory}}
          python-version: 3.11.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and deploy
        run: |
          echo VERCEL_TOKEN=${{ secrets.VERCELTOKEN }} > .env
          echo VERCEL_ORG_ID=${{ secrets.VERCELORGID }} >> .env
          echo VERCEL_PROJECT_ID=${{ secrets.VERCELPYTHONPROJECTID}} >> .env
          vercel --token ${{ secrets.VERCELTOKEN }} --confirm --env .env
