name: CI/CD Python Pipeline

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./recommendation-system"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build
        run: |
          export FLASK_APP=api/main.py
          run flask run --host=0.0.0.0 --port=5000 &

      - name: Wait for Flask to start
        run: sleep 5

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCELORGID }}
          vercel-project-id: ${{ secrets.VERCELPYTHONPROJECTID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
